language: cpp
# run on new infrastructure
sudo: false
cache:
  apt: true
  directories:
    /home/travis/tmp/riscv-gnu-toolchain
    $RISCV
    $VERILATOR_ROOT

# required packages to install
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - gperf
      - autoconf
      - automake
      - autotools-dev
      - libmpc-dev
      - libmpfr-dev
      - libgmp-dev
      - gawk
      - build-essential
      - bison
      - flex
      - texinfo
      - python-pexpect
      - libusb-1.0-0-dev
      - default-jdk
      - zlib1g-dev
      - valgrind
env:
  global:
    - RISCV="/home/travis/riscv_install"
    - VERILATOR_ROOT="/home/travis/verilator-3.924/"

branches:
  only:
  - master
  - ariane_next

before_install:
  - export CXX=g++-7 CC=gcc-7
  # setup dependent paths
  - export PATH=$RISCV/bin:$VERILATOR_ROOT/bin:$PATH
  - export LIBRARY_PATH=$RISCV/lib
  - export LD_LIBRARY_PATH=$RISCV/lib
  - export C_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/include
  - export CPLUS_INCLUDE_PATH=$RISCV/include:$VERILATOR_ROOT/include
  # number of parallel jobs to use for make commands and simulation
  - export NUM_JOBS=4
  - ci/make-tmp.sh
  - git submodule update --init --recursive

stages:
  - checkout
  - compile1
  - compile2
  - test

jobs:
  include:
    - stage: checkout
      name: checkout gcc
      script:
        - ci/build-riscv-gcc.sh 0
    - stage: compile1
      name: build gcc
      script:
        - ci/build-riscv-gcc.sh 1
    - stage: compile2
      name: build tools
      script:
        - ci/install-fesvr.sh
        - ci/install-verilator.sh
        - ci/install-dtc.sh
        - ci/install-spike.sh
    - stage: test
      name: run riscv benchmarks
      script:
        - ci/build-riscv-tests.sh
        - make -j${NUM_JOBS} run-benchmarks-verilator
    # rv64ui-p-* tests
    - stage: test
      name: run asm tests1
      script:
        - ci/build-riscv-tests.sh
        - make -j${NUM_JOBS} run-asm-tests1-verilator
    # rv64ui-v-* tests
    - stage: test
      name: run asm tests2
      script:
        - ci/build-riscv-tests.sh
        - make -j${NUM_JOBS} run-asm-tests2-verilator
    # rv64um-*-* tests
    - stage: test
      name: run mul tests
      script:
        - ci/build-riscv-tests.sh
        - make -j${NUM_JOBS} run-mul-verilator
    # amo tests
    - stage: test
      name: run amo tests
      script:
        - ci/build-riscv-tests.sh
        - make -j${NUM_JOBS} run-amo-verilator
    - stage: test
      name: run torture
      script:
        - ci/get-torture.sh
        - make clean
        - make torture-gen
        - make torture-rtest-verilator

    - stage: test
      name: run riscv benchmarks (serpent)
      script:
        - ci/build-riscv-tests.sh
        - make -j${NUM_JOBS} run-benchmarks-verilator  defines=PITON_ARIANE+AXI64_CACHE_PORTS
    # rv64ui-p-* tests
    - stage: test
      name: run asm tests1 (serpent)
      script:
        - ci/build-riscv-tests.sh
        - make -j${NUM_JOBS} run-asm-tests1-verilator  defines=PITON_ARIANE+AXI64_CACHE_PORTS
    # rv64ui-v-* tests
    - stage: test
      name: run asm tests2 (serpent)
      script:
        - ci/build-riscv-tests.sh
        - make -j${NUM_JOBS} run-asm-tests2-verilator  defines=PITON_ARIANE+AXI64_CACHE_PORTS

    - stage: test
      name: run torture (serpent)
      script:
        - ci/get-torture.sh
        - make clean
        - make torture-gen defines=PITON_ARIANE+AXI64_CACHE_PORTS
        - make torture-rtest-verilator defines=PITON_ARIANE+AXI64_CACHE_PORTS



# extra time during long builds
install: travis_wait
