#   Copyright (c) 2024 OpenHW Group
#   Copyright (c) 2024 Thales
#   SPDX-License-Identifier: Apache-2.0 WITH SHL-2.1
#   Author: Abdessamii Oukalrazqou


misa:
    reset-val: 0x40001106      

mcountinhibit: 
    rv32 : 
        accessible : false
pmpaddr0:
    reset-val: 0x0       
#  Range control
pmpaddr : 
    range: 8
pmpcfg :
    range : 2
    
exclude :         
    key : priv_mode       
    cond : S
exclude :         
    key : priv_mode       
    cond : U
    

