spike_param_tree:
  bootrom: true
  bootrom_base: 65536
  bootrom_size: 4096
  dram: true
  dram_base: 2147483648
  dram_size: 1073741824
  generic_core_config: false
  max_steps: 200000
  max_steps_enabled: false
  isa: rv32imczicsr_zcb_zba_zbb_zbc_zbs
  priv: M
  core_configs:
    -
      isa: rv32imczicsr_zcb_zba_zbb_zbc_zbs
      extensions: cv32a60x,cvxif
      boot_addr: 2147483648
      marchid_override_mask: 0xFFFFFFFF
      marchid_override_value: 0x3
      misa_write_mask: 0x0
      pmpaddr0: 0
      pmpcfg0: 0
      pmpregions_max: 64
      pmpregions_writable: 8
      priv: M
      status_fs_field_we: false
      status_fs_field_we_enable: false
      status_vs_field_we: false
      status_vs_field_we_enable: false
      mstatus_write_mask: 136
      mstatus_override_mask: 6144
      mie_write_mask: 0x00000880
      mie_override_mask: 0xfffff77f
      mie_override_value: 0x00000000
      mip_write_mask: 0x00000000
      mip_override_mask: 0xfffff77f
      mip_override_value: 0x00000000
      mtval_write_mask: 0
      tinfo_accessible: 0
      mscontext_accessible: 0
      mcontext_accessible: 0
      tdata1_accessible: 0
      tdata2_accessible: 0
      tdata3_accessible: 0
      tselect_accessible: 0
      mhartid: 0
      mvendorid_override_mask : 0xFFFFFFFF
      mvendorid_override_value: 1538
      csr_counters_injection: true
      interrupts_injection: true
      unified_traps: true
      mcycleh_implemented: false
      mhpmevent31_implemented: false
